# Generated by Django 5.2 on 2025-04-09 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TauxDeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monnaie_locale', models.CharField(max_length=20)),
                ('monnaie_etrangere', models.CharField(max_length=20)),
                ('taux_du_jour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('est_reference', models.BooleanField(default=False)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de changes',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('pseudo', models.CharField(max_length=60, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_superuser', models.BooleanField(default=False, editable=False)),
                ('vu_a', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('user_permissions', models.ManyToManyField(to='auth.permission')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueTauxDeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Taux de Change',
                'verbose_name_plural': 'Historiques Taux de Change',
            },
        ),
        migrations.CreateModel(
            name='ConversionDeDevise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monnaie_locale', models.CharField(max_length=20)),
                ('monnaie_etrangere', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_converti', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_du_jour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('historique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='exchangeApi.historiquetauxdechange')),
            ],
            options={
                'verbose_name': 'Conversion de Devise',
                'verbose_name_plural': 'Conversions de Devise',
            },
        ),
    ]
